"""Add profile_photo to user

Revision ID: 5280d6643ee8
Revises: 
Create Date: 2026-01-17 15:09:05.993138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5280d6643ee8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.create_index('idx_user_category', ['user_id', 'category'], unique=False)
        batch_op.create_index('idx_user_date', ['user_id', 'date_added'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_date_added'), ['date_added'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=500), nullable=True))
        batch_op.drop_constraint(batch_op.f('user_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('user_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_unique_constraint(batch_op.f('user_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('user_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('profile_photo')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_user_id'))
        batch_op.drop_index(batch_op.f('ix_expense_date_added'))
        batch_op.drop_index('idx_user_date')
        batch_op.drop_index('idx_user_category')
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
