"""Add notification preferences to user

Revision ID: 8f03fdbcc3db
Revises: 5280d6643ee8
Create Date: 2026-01-17 18:23:48.309579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f03fdbcc3db'
down_revision = '5280d6643ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_daily_reminders', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('notify_budget_alerts', sa.Boolean(), nullable=False, server_default=sa.text('true')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notify_budget_alerts')
        batch_op.drop_column('notify_daily_reminders')

    # ### end Alembic commands ###
